// NYUCHI DESIGN TOKENS — N1
// Rust — generated by scripts/sync-tokens.ts from the Supabase
// document store (styling-minerals, styling-heritage-colors).
//
// DO NOT EDIT BY HAND. Run `pnpm tokens:sync`; `pnpm tokens:verify`
// fails the build if this file drifts from the database.
//
// `nyuchi-tokens.ts` has declared a Rust target ("const values + config
// structs") since the file was written, and nothing ever emitted one. This is
// that file, and it is what the Dioxus half of the registry consumes.

#![allow(dead_code)]

// ─── Seven African Minerals ─────────────────────────────────────────────────
pub const COBALT_DARK: &str = "#00B0FF";
pub const COBALT_LIGHT: &str = "#0047AB";
pub const TANZANITE_DARK: &str = "#B388FF";
pub const TANZANITE_LIGHT: &str = "#4B0082";
pub const MALACHITE_DARK: &str = "#64FFDA";
pub const MALACHITE_LIGHT: &str = "#004D40";
pub const GOLD_DARK: &str = "#FFD740";
pub const GOLD_LIGHT: &str = "#5D4037";
pub const TERRACOTTA_DARK: &str = "#E1B07E";
pub const TERRACOTTA_LIGHT: &str = "#A0522D";
pub const SODALITE_DARK: &str = "#3D5AFE";
pub const SODALITE_LIGHT: &str = "#283593";
pub const COPPER_DARK: &str = "#FF8A65";
pub const COPPER_LIGHT: &str = "#BF5A36";

// ─── Seven Heritage tones ───────────────────────────────────────────────────
pub const INDIGO_DARK: &str = "#7986CB";
pub const INDIGO_LIGHT: &str = "#4527A0";
pub const SAVANNA_DARK: &str = "#E5C158";
pub const SAVANNA_LIGHT: &str = "#8D6E1A";
pub const BAOBAB_DARK: &str = "#A1887F";
pub const BAOBAB_LIGHT: &str = "#4E342E";
pub const SUNSET_DARK: &str = "#FF7043";
pub const SUNSET_LIGHT: &str = "#D84315";
pub const RIVER_DARK: &str = "#4DD0E1";
pub const RIVER_LIGHT: &str = "#006064";
pub const HEMATITE_DARK: &str = "#90A4AE";
pub const HEMATITE_LIGHT: &str = "#546E7A";
pub const KALAHARI_DARK: &str = "#E8D9B5";
pub const KALAHARI_LIGHT: &str = "#C9B589";

/// Every palette colour for one theme. Construct with [`Palette::dark`] or
/// [`Palette::light`] rather than by hand, so a new colour cannot be missed.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Palette {
    pub cobalt: &'static str,
    pub tanzanite: &'static str,
    pub malachite: &'static str,
    pub gold: &'static str,
    pub terracotta: &'static str,
    pub sodalite: &'static str,
    pub copper: &'static str,
    pub indigo: &'static str,
    pub savanna: &'static str,
    pub baobab: &'static str,
    pub sunset: &'static str,
    pub river: &'static str,
    pub hematite: &'static str,
    pub kalahari: &'static str,
}

impl Palette {
    pub const fn dark() -> Self {
        Self {
        cobalt: COBALT_DARK,
        tanzanite: TANZANITE_DARK,
        malachite: MALACHITE_DARK,
        gold: GOLD_DARK,
        terracotta: TERRACOTTA_DARK,
        sodalite: SODALITE_DARK,
        copper: COPPER_DARK,
        indigo: INDIGO_DARK,
        savanna: SAVANNA_DARK,
        baobab: BAOBAB_DARK,
        sunset: SUNSET_DARK,
        river: RIVER_DARK,
        hematite: HEMATITE_DARK,
        kalahari: KALAHARI_DARK,
        }
    }

    pub const fn light() -> Self {
        Self {
        cobalt: COBALT_LIGHT,
        tanzanite: TANZANITE_LIGHT,
        malachite: MALACHITE_LIGHT,
        gold: GOLD_LIGHT,
        terracotta: TERRACOTTA_LIGHT,
        sodalite: SODALITE_LIGHT,
        copper: COPPER_LIGHT,
        indigo: INDIGO_LIGHT,
        savanna: SAVANNA_LIGHT,
        baobab: BAOBAB_LIGHT,
        sunset: SUNSET_LIGHT,
        river: RIVER_LIGHT,
        hematite: HEMATITE_LIGHT,
        kalahari: KALAHARI_LIGHT,
        }
    }
}

/// Spacing scale, in pixels.
pub struct Spacing;

impl Spacing {
    pub const XS: u32 = 4;
    pub const SM: u32 = 8;
    pub const MD: u32 = 12;
    pub const BASE: u32 = 16;
    pub const LG: u32 = 24;
    pub const XL: u32 = 32;
}

/// Radius scale, in pixels. Every value derives from the 7px unit.
pub struct Radius;

impl Radius {
    pub const SM: u32 = 7;
    pub const MD: u32 = 12;
    pub const LG: u32 = 14;
    pub const XL: u32 = 17;
    pub const FULL: u32 = 9999;
}

/// The canonical type stack.
pub struct Fonts;

impl Fonts {
    pub const SANS: &'static str = "Noto Sans";
    pub const SERIF: &'static str = "Noto Serif";
    pub const MONO: &'static str = "JetBrains Mono";
}
