//! Lowering a service to Rust and axum (RFC-0011 §8).
//!
//! `mz build` writes one Cargo package: a `Cargo.toml`, a `src/main.rs`, and the fixtures
//! the service embeds. The `main.rs` has three parts:
//!
//! - **the runtime**, [`RUNTIME`], emitted verbatim: RFC-0011 §6's algorithm as one
//!   function, the query decoding rule of §4.2, and the axum glue. axum is the server, not
//!   the router, so there is one routing semantics (HD-5);
//! - **the service**, generated: the route table, one plain `fn` per route, and the
//!   fallback;
//! - **the tests**, generated: one `#[tokio::test]` per `example`, sent to the router with
//!   `oneshot`, so the lowering is checked against the same clauses `mz contract` evaluates.
//!
//! The generated code holds no `unwrap`, `expect`, indexing or `panic!` on a request path
//! (RFC-0011 §5). The compiler itself still has no dependencies; the generated package
//! depends on exactly pinned `axum` and `tokio`, and its tests on `tower`, `http-body-util`
//! and `serde_json`.

use std::collections::BTreeMap;
use std::fmt::Write as _;

use crate::ast::TypeKind;
use crate::resolve::Ty;
use crate::service::{
    Body, Check, ClauseKind, Cond, CondTest, Facet, Lit, Pred, RecordLit, Route, Segment, Service,
    Stmt, Value, query_type, segments,
};

/// The generated package, as `(relative path, contents)` pairs. Fixtures are listed by
/// path only; the caller copies them from beside the `.mz` file.
pub struct Package {
    /// `Cargo.toml` and `src/main.rs`.
    pub files: Vec<(String, String)>,
    /// Fixture paths, relative to the `.mz` file and to the package root alike.
    pub fixtures: Vec<String>,
}

/// Exact pins for the generated package. Changing one is a change to the lowering.
pub const PINS: &[(&str, &str)] = &[
    ("axum", "=0.8.9"),
    ("tokio", "=1.53.1"),
    ("tower", "=0.5.3"),
    ("http-body-util", "=0.1.5"),
    ("serde_json", "=1.0.151"),
];

fn pin(name: &str) -> &'static str {
    PINS.iter()
        .find(|(n, _)| *n == name)
        .map(|(_, v)| *v)
        .unwrap_or("*")
}

/// Lower a checked service. `source` is the file name it came from, for the header.
pub fn lower(service: &Service, source: &str) -> Package {
    let mut fixtures = Vec::new();
    for r in &service.routes {
        files_in(&r.handler.body, &mut fixtures);
    }
    if let Some(f) = &service.fallback {
        files_in(&f.body, &mut fixtures);
    }
    fixtures.sort();
    fixtures.dedup();
    let cargo = cargo_toml(service, source);
    let mut main = String::new();
    writeln!(
        main,
        "//! Generated by `mz build` from `{source}`. Do not edit: change the `.mz` file and\n//! build again (RFC-0011 §8). `service {}`.\n",
        service.name
    )
    .unwrap();
    main.push_str(RUNTIME);
    main.push_str(&service_code(service));
    main.push_str(&tests(service));
    Package {
        files: vec![
            ("Cargo.toml".to_string(), cargo),
            ("src/main.rs".to_string(), main),
        ],
        fixtures,
    }
}

fn files_in(stmts: &[Stmt], out: &mut Vec<String>) {
    for s in stmts {
        match s {
            Stmt::Respond(r) => {
                if let Body::File(p, _) = &r.body {
                    out.push(p.clone());
                }
            }
            Stmt::When { then, els, .. } => {
                files_in(then, out);
                if let Some(e) = els {
                    files_in(e, out);
                }
            }
            Stmt::Header(_) => {}
        }
    }
}

fn cargo_toml(service: &Service, source: &str) -> String {
    format!(
        r#"# Generated by `mz build` from `{source}`. Do not edit (RFC-0011 §8).
[package]
name = "mz-{name}"
version = "0.0.0"
edition = "2024"
publish = false

# Its own workspace root, so it never joins a surrounding workspace.
[workspace]

[dependencies]
axum = {{ version = "{axum}", default-features = false, features = ["http1", "tokio"] }}
tokio = {{ version = "{tokio}", features = ["rt-multi-thread", "macros", "net"] }}

[dev-dependencies]
tower = {{ version = "{tower}", features = ["util"] }}
http-body-util = "{hbu}"
serde_json = "{sj}"
"#,
        name = service.name.replace('_', "-"),
        axum = pin("axum"),
        tokio = pin("tokio"),
        tower = pin("tower"),
        hbu = pin("http-body-util"),
        sj = pin("serde_json"),
    )
}

/// A Rust string literal for `s`.
fn lit(s: &str) -> String {
    format!("{s:?}")
}

/// The generated variable for a parameter. Prefixed, so a parameter called `type` or
/// `match` is still a Rust identifier.
fn var(name: &str) -> String {
    format!("p_{name}")
}

/// What a name holds at a point in a handler: its scalar type, and whether it is still an
/// option there (not narrowed).
type Scope = BTreeMap<String, (Ty, bool)>;

fn service_code(service: &Service) -> String {
    let mut out = String::new();
    out.push_str("\n// ---- the service, generated ----\n\n");
    // Service headers.
    out.push_str("static SERVICE_HEADERS: &[(&str, &str)] = &[\n");
    for h in &service.headers {
        writeln!(
            out,
            "    ({}, {}),",
            lit(&h.name.to_ascii_lowercase()),
            lit(&h.value)
        )
        .unwrap();
    }
    out.push_str("];\n\n");
    // Route table.
    out.push_str("static ROUTES: &[RouteDef] = &[\n");
    let routes: Vec<(usize, &Route, Vec<Segment>)> = service
        .routes
        .iter()
        .enumerate()
        .filter_map(|(i, r)| {
            let segs = r.pattern.as_ref().and_then(|(p, _)| segments(p))?;
            r.method?;
            Some((i, r, segs))
        })
        .collect();
    for (i, r, segs) in &routes {
        let method = r.method.map_or("Get", |(m, _)| variant(m.http()));
        let segs: Vec<String> = segs
            .iter()
            .map(|s| match s {
                Segment::Literal(l) => format!("Seg::Lit({})", lit(l)),
                Segment::Param(_) => "Seg::Param".to_string(),
            })
            .collect();
        writeln!(
            out,
            "    RouteDef {{ method: Method::{method}, segs: &[{}], id: {i} }},",
            segs.join(", ")
        )
        .unwrap();
    }
    out.push_str("];\n\n");
    // Dispatch by id.
    out.push_str(
        "fn call(id: usize, params: Vec<String>, query: &[(String, String)]) -> Reply {\n    let mut params = params.into_iter();\n    match id {\n",
    );
    for (i, r, segs) in &routes {
        let mut args = Vec::new();
        let mut binds = String::new();
        for s in segs {
            if let Segment::Param(p) = s {
                writeln!(
                    binds,
                    "            let {} = params.next().unwrap_or_default();",
                    var(p)
                )
                .unwrap();
                args.push(var(p));
            }
        }
        for q in &r.queries {
            let f = match query_type(&q.ty) {
                Some(Ty::Int) => "q_int",
                Some(Ty::Bool) => "q_bool",
                _ => "q_text",
            };
            writeln!(
                binds,
                "            let {} = {f}(query, {});",
                var(&q.name),
                lit(&q.name)
            )
            .unwrap();
            args.push(var(&q.name));
        }
        writeln!(
            out,
            "        {i} => {{\n{binds}            route_{}({})\n        }}",
            r.name,
            args.join(", ")
        )
        .unwrap();
    }
    out.push_str("        _ => reply(500, Vec::new(), Vec::new(), None),\n    }\n}\n\n");
    // Handlers.
    for (_, r, segs) in &routes {
        let mut scope: Scope = BTreeMap::new();
        let mut params = Vec::new();
        for s in segs {
            if let Segment::Param(p) = s {
                scope.insert(p.clone(), (Ty::Text, false));
                params.push(format!("{}: String", var(p)));
            }
        }
        for q in &r.queries {
            let ty = query_type(&q.ty).unwrap_or(Ty::Text);
            params.push(format!("{}: Option<{}>", var(&q.name), rust_ty(&ty)));
            scope.insert(q.name.clone(), (ty, true));
        }
        writeln!(
            out,
            "/// `route {}`.\nfn route_{}({}) -> Reply {{\n    let mut h: Vec<(String, String)> = Vec::new();",
            r.name,
            r.name,
            params.join(", ")
        )
        .unwrap();
        block(&mut out, &r.handler.body, &scope, service, 1);
        out.push_str("}\n\n");
    }
    // Fallback.
    out.push_str(
        "/// The `fallback`, or a bare 404 when the service has none.\nfn fallback() -> Reply {\n",
    );
    match &service.fallback {
        Some(f) => {
            out.push_str("    let mut h: Vec<(String, String)> = Vec::new();\n");
            block(&mut out, &f.body, &BTreeMap::new(), service, 1);
        }
        None => out.push_str("    reply(404, Vec::new(), Vec::new(), None)\n"),
    }
    out.push_str("}\n");
    out
}

fn variant(http: &str) -> &'static str {
    match http {
        "GET" => "Get",
        "HEAD" => "Head",
        "POST" => "Post",
        "PUT" => "Put",
        "PATCH" => "Patch",
        "DELETE" => "Delete",
        _ => "Options",
    }
}

fn rust_ty(ty: &Ty) -> &'static str {
    match ty {
        Ty::Int => "i64",
        Ty::Bool => "bool",
        _ => "String",
    }
}

fn indent(depth: usize) -> String {
    "    ".repeat(depth)
}

/// Statements, mirroring `serve::Runtime::block`: headers accumulate in `h` along the
/// path, a `when` that does not respond falls through, and `respond` returns.
fn block(out: &mut String, stmts: &[Stmt], scope: &Scope, service: &Service, depth: usize) {
    let pad = indent(depth);
    for stmt in stmts {
        match stmt {
            Stmt::Header(hl) => {
                writeln!(
                    out,
                    "{pad}h.push(({}.to_string(), {}));",
                    lit(&hl.name.to_ascii_lowercase()),
                    interpolation(&hl.value, scope)
                )
                .unwrap();
            }
            Stmt::When {
                cond: Some(c),
                then,
                els,
                ..
            } => {
                if let CondTest::IsNone(_) = c.test {
                    let v = var(&c.subject);
                    match els {
                        Some(e) => {
                            // `when p is none … else …`: the `else` sees `p` narrowed.
                            let mut narrowed = scope.clone();
                            if let Some(entry) = narrowed.get_mut(&c.subject) {
                                entry.1 = false;
                            }
                            writeln!(out, "{pad}if let Some({v}) = {v}.clone() {{").unwrap();
                            block(out, e, &narrowed, service, depth + 1);
                            writeln!(out, "{pad}}} else {{").unwrap();
                            block(out, then, scope, service, depth + 1);
                            writeln!(out, "{pad}}}").unwrap();
                        }
                        None => {
                            writeln!(out, "{pad}if {v}.is_none() {{").unwrap();
                            block(out, then, scope, service, depth + 1);
                            writeln!(out, "{pad}}}").unwrap();
                        }
                    }
                } else {
                    writeln!(out, "{pad}if {} {{", condition(c)).unwrap();
                    block(out, then, scope, service, depth + 1);
                    match els {
                        Some(e) => {
                            writeln!(out, "{pad}}} else {{").unwrap();
                            block(out, e, scope, service, depth + 1);
                            writeln!(out, "{pad}}}").unwrap();
                        }
                        None => writeln!(out, "{pad}}}").unwrap(),
                    }
                }
            }
            // A condition that did not parse never reaches the lowering: `mz build`
            // lowers only a file with no errors.
            Stmt::When { cond: None, .. } => {}
            Stmt::Respond(r) => {
                let status = r.status.map_or(500, |(s, _)| s);
                let (body, ct) = match &r.body {
                    Body::Empty => ("Vec::new()".to_string(), "None".to_string()),
                    Body::Text(t, _) => (
                        format!("{}.into_bytes()", interpolation(t, scope)),
                        "Some(\"text/plain; charset=utf-8\")".to_string(),
                    ),
                    Body::File(p, _) => (
                        format!(
                            "include_bytes!(concat!(env!(\"CARGO_MANIFEST_DIR\"), \"/\", {})).to_vec()",
                            lit(p)
                        ),
                        format!("Some({})", lit(crate::serve::content_type_for(p))),
                    ),
                    Body::Json(l) => (
                        json_expr(l, scope, service, depth),
                        "Some(\"application/json\")".to_string(),
                    ),
                };
                writeln!(out, "{pad}return reply({status}, h, {body}, {ct});").unwrap();
            }
        }
    }
}

fn condition(c: &Cond) -> String {
    let v = var(&c.subject);
    let eq = |l: &Lit| match l {
        Lit::Text(t) => format!("{v} == {}", lit(t)),
        Lit::Int(n) => format!("{v} == {n}"),
        Lit::Bool(b) => format!("{v} == {b}"),
        Lit::None => "false".to_string(),
    };
    let test = match &c.test {
        CondTest::Truth => v.clone(),
        CondTest::Is(l, _) => eq(l),
        CondTest::In(set) => set
            .iter()
            .map(|(l, _)| eq(l))
            .collect::<Vec<_>>()
            .join(" || "),
        CondTest::AtLeast(n, _) => format!("{v} >= {n}"),
        CondTest::AtMost(n, _) => format!("{v} <= {n}"),
        CondTest::IsNone(_) => format!("{v}.is_none()"),
    };
    if c.negated {
        format!("!({test})")
    } else {
        test
    }
}

/// A `format!` for a string with `{name}` interpolations, or a plain `String`.
fn interpolation(text: &str, scope: &Scope) -> String {
    let mut fmt = String::new();
    let mut args = Vec::new();
    let mut rest = text;
    while let Some(open) = rest.find('{') {
        fmt.push_str(&rest[..open].replace('}', "}}"));
        let after = &rest[open + 1..];
        let Some(close) = after.find('}') else {
            fmt.push_str(&rest[open..].replace('{', "{{").replace('}', "}}"));
            rest = "";
            break;
        };
        let name = after[..close].trim();
        if scope.contains_key(name) {
            fmt.push_str("{}");
            args.push(var(name));
        }
        rest = &after[close + 1..];
    }
    fmt.push_str(&rest.replace('}', "}}"));
    if args.is_empty() {
        format!(
            "{}.to_string()",
            lit(&fmt.replace("{{", "{").replace("}}", "}"))
        )
    } else {
        format!("format!({}, {})", lit(&fmt), args.join(", "))
    }
}

/// A block expression building a record literal's JSON, fields in declaration order.
fn json_expr(l: &RecordLit, scope: &Scope, service: &Service, depth: usize) -> String {
    let pad = indent(depth + 1);
    let mut out = String::from("{\n");
    writeln!(out, "{pad}let mut b = String::from(\"{{\");").unwrap();
    let Some(decl) = service.records.iter().find(|r| r.name == l.record) else {
        return "b\"{}\".to_vec()".to_string();
    };
    for (i, f) in decl.fields.iter().enumerate() {
        let key = format!(
            "{}{}:",
            if i > 0 { "," } else { "" },
            crate::diagnostic::json_string(&f.name)
        );
        writeln!(out, "{pad}b.push_str({});", lit(&key)).unwrap();
        let field_is_option = matches!(&f.ty.kind, TypeKind::Apply(c, _) if c == "option");
        let value = l.fields.iter().find(|(n, _, _)| *n == f.name).map(|x| &x.2);
        let code = match value {
            None | Some(Value::Lit(Lit::None, _)) => "b.push_str(\"null\");".to_string(),
            Some(Value::Lit(Lit::Text(t), _)) => {
                format!("json_str(&mut b, &{});", interpolation(t, scope))
            }
            Some(Value::Lit(Lit::Int(n), _)) => format!("b.push_str({});", lit(&n.to_string())),
            Some(Value::Lit(Lit::Bool(x), _)) => format!("b.push_str({});", lit(&x.to_string())),
            Some(Value::Name(n, _)) => match scope.get(n) {
                // Not a parameter: an enum variant, serialised as its name.
                None => format!("json_str(&mut b, {});", lit(n)),
                Some((ty, true)) if field_is_option => format!(
                    "match &{} {{ Some(v) => {}, None => b.push_str(\"null\") }}",
                    var(n),
                    scalar_json(ty, "v")
                ),
                Some((ty, _)) => format!("{};", scalar_json(ty, &format!("&{}", var(n)))),
            },
        };
        writeln!(out, "{pad}{code}").unwrap();
    }
    writeln!(out, "{pad}b.push('}}');").unwrap();
    write!(out, "{pad}b.into_bytes()\n{}}}", indent(depth)).unwrap();
    out
}

fn scalar_json(ty: &Ty, v: &str) -> String {
    match ty {
        Ty::Text => format!("json_str(&mut b, {v})"),
        _ => format!("b.push_str(&{v}.to_string())"),
    }
}

fn tests(service: &Service) -> String {
    let mut out = String::from(TESTS_HEAD);
    let Some(contract) = &service.contract else {
        out.push_str("}\n");
        return out;
    };
    for clause in &contract.clauses {
        let ClauseKind::Example {
            method,
            target,
            check,
        } = &clause.kind
        else {
            continue;
        };
        let written = clause.canonical();
        writeln!(
            out,
            "\n    /// `{}`\n    #[tokio::test]\n    async fn example_line_{}() {{\n        let got = send({}, {}).await;\n        assert!(holds(&got, {}), \"{{}}: {{}}\", {}, describe(&got));\n    }}",
            written.replace('`', "'"),
            clause.span.start_line,
            lit(method.http()),
            lit(target),
            check_code(check),
            lit(&written),
        )
        .unwrap();
    }
    out.push_str("}\n");
    out
}

fn check_code(c: &Check) -> String {
    let facet = match &c.facet {
        Facet::Status => "F::Status".to_string(),
        Facet::Header(n) => format!("F::Header({})", lit(n)),
        Facet::Body => "F::Body".to_string(),
        Facet::BodyPath(p) => format!("F::Path({})", lit(&format!("/{}", p.join("/")))),
    };
    let l = |v: &Lit| match v {
        Lit::Int(n) => format!("L::Int({n})"),
        Lit::Text(t) => format!("L::Text({})", lit(t)),
        Lit::Bool(b) => format!("L::Bool({b})"),
        Lit::None => "L::None".to_string(),
    };
    let pred = match &c.pred {
        Pred::Is(v) => format!("P::Is({})", l(v)),
        Pred::In(vs) => format!(
            "P::In(&[{}])",
            vs.iter().map(l).collect::<Vec<_>>().join(", ")
        ),
        Pred::NotEmpty => "P::NotEmpty".to_string(),
        Pred::Contains(t) => format!("P::Contains({})", lit(t)),
        Pred::AtLeast(n) => format!("P::AtLeast({n})"),
        Pred::AtMost(n) => format!("P::AtMost({n})"),
    };
    format!("{facet}, {pred}")
}

/// The runtime every lowered service shares: RFC-0011 §6 and §4.2, and the axum glue.
pub const RUNTIME: &str = r##"#![forbid(unsafe_code)]
#![allow(unused_mut, unused_variables, dead_code, clippy::all)]

// ---- the runtime: RFC-0011 §6, emitted verbatim by `mz build` ----

use axum::Router;
use axum::body::Body;
use axum::extract::Request;
use axum::http::{HeaderName, HeaderValue, Response, StatusCode};

/// A response before it becomes an axum `Response`.
pub struct Reply {
    status: u16,
    headers: Vec<(String, String)>,
    body: Vec<u8>,
}

#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord)]
enum Method {
    Get,
    Head,
    Post,
    Put,
    Patch,
    Delete,
    Options,
}

impl Method {
    const ALL: [Method; 7] = [
        Method::Get,
        Method::Head,
        Method::Post,
        Method::Put,
        Method::Patch,
        Method::Delete,
        Method::Options,
    ];

    fn http(self) -> &'static str {
        match self {
            Method::Get => "GET",
            Method::Head => "HEAD",
            Method::Post => "POST",
            Method::Put => "PUT",
            Method::Patch => "PATCH",
            Method::Delete => "DELETE",
            Method::Options => "OPTIONS",
        }
    }

    fn from_http(token: &str) -> Option<Method> {
        Method::ALL.into_iter().find(|m| m.http() == token)
    }
}

enum Seg {
    Lit(&'static str),
    Param,
}

struct RouteDef {
    method: Method,
    segs: &'static [Seg],
    id: usize,
}

/// A response with a default `content-type` unless the handler set one.
fn reply(
    status: u16,
    mut headers: Vec<(String, String)>,
    body: Vec<u8>,
    content_type: Option<&str>,
) -> Reply {
    if let Some(ct) = content_type
        && !headers.iter().any(|(n, _)| n == "content-type")
    {
        headers.push(("content-type".to_string(), ct.to_string()));
    }
    Reply {
        status,
        headers,
        body,
    }
}

/// Step 1: the `location` of a `308`, when `path` is not canonical.
fn canonical_redirect(path: &str, query: Option<&str>) -> Option<String> {
    if path == "/" || !path.starts_with('/') {
        return None;
    }
    let parts: Vec<&str> = path.split('/').skip(1).collect();
    if !parts.iter().any(|p| p.is_empty()) {
        return None;
    }
    let kept: Vec<&str> = parts.into_iter().filter(|p| !p.is_empty()).collect();
    let mut location = format!("/{}", kept.join("/"));
    if let Some(q) = query {
        location.push('?');
        location.push_str(q);
    }
    Some(location)
}

fn match_key(segs: &[Seg], raw: &[&str]) -> Option<Vec<bool>> {
    if segs.len() != raw.len() {
        return None;
    }
    let mut key = Vec::with_capacity(segs.len());
    for (seg, value) in segs.iter().zip(raw) {
        match seg {
            Seg::Lit(l) if l == value => key.push(false),
            Seg::Lit(_) => return None,
            Seg::Param => key.push(true),
        }
    }
    Some(key)
}

fn allow(declared: impl Iterator<Item = Method>) -> String {
    let mut set: Vec<Method> = declared.collect();
    if set.contains(&Method::Get) {
        set.push(Method::Head);
    }
    set.push(Method::Options);
    Method::ALL
        .into_iter()
        .filter(|m| set.contains(m))
        .map(Method::http)
        .collect::<Vec<_>>()
        .join(", ")
}

fn hex(b: u8) -> Option<u8> {
    match b {
        b'0'..=b'9' => Some(b - b'0'),
        b'a'..=b'f' => Some(b - b'a' + 10),
        b'A'..=b'F' => Some(b - b'A' + 10),
        _ => None,
    }
}

/// Percent-decode; with `plus`, `+` is a space. A malformed escape is kept as written.
fn percent_decode(s: &str, plus: bool) -> String {
    let bytes = s.as_bytes();
    let mut out = Vec::with_capacity(bytes.len());
    let mut i = 0;
    while i < bytes.len() {
        let b = bytes[i];
        if b == b'%'
            && let (Some(h), Some(l)) = (
                bytes.get(i + 1).copied().and_then(hex),
                bytes.get(i + 2).copied().and_then(hex),
            )
        {
            out.push(h * 16 + l);
            i += 3;
            continue;
        }
        out.push(if plus && b == b'+' { b' ' } else { b });
        i += 1;
    }
    String::from_utf8_lossy(&out).into_owned()
}

/// RFC-0011 §4.2: form-urlencoded pairs, decoded; the first occurrence of a name wins.
fn parse_query(q: &str) -> Vec<(String, String)> {
    q.split('&')
        .filter(|p| !p.is_empty())
        .map(|p| match p.split_once('=') {
            Some((k, v)) => (percent_decode(k, true), percent_decode(v, true)),
            None => (percent_decode(p, true), String::new()),
        })
        .collect()
}

fn q_text(q: &[(String, String)], name: &str) -> Option<String> {
    q.iter().find(|(k, _)| k == name).map(|(_, v)| v.clone())
}

fn q_int(q: &[(String, String)], name: &str) -> Option<i64> {
    let v = q_text(q, name)?;
    let digits = v.strip_prefix('-').unwrap_or(&v);
    if !digits.is_empty() && digits.bytes().all(|b| b.is_ascii_digit()) {
        v.parse().ok()
    } else {
        None
    }
}

fn q_bool(q: &[(String, String)], name: &str) -> Option<bool> {
    match q_text(q, name)?.as_str() {
        "true" => Some(true),
        "false" => Some(false),
        _ => None,
    }
}

fn json_str(out: &mut String, s: &str) {
    out.push('"');
    for c in s.chars() {
        match c {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            c if (c as u32) < 0x20 => out.push_str(&format!("\\u{:04x}", c as u32)),
            c => out.push(c),
        }
    }
    out.push('"');
}

/// RFC-0011 §6, steps 1–4.
pub fn dispatch(method: &str, target: &str) -> Reply {
    let mut reply = route(method, target);
    for (name, value) in SERVICE_HEADERS {
        if !reply.headers.iter().any(|(n, _)| n == name) {
            reply.headers.push((name.to_string(), value.to_string()));
        }
    }
    reply
}

fn route(method: &str, target: &str) -> Reply {
    let (path, query) = match target.split_once('?') {
        Some((p, q)) => (p, Some(q)),
        None => (target, None),
    };
    if let Some(location) = canonical_redirect(path, query) {
        return reply(308, vec![("location".to_string(), location)], Vec::new(), None);
    }
    let raw: Vec<&str> = path.split('/').skip(1).filter(|s| !s.is_empty()).collect();
    let mut best: Option<(Vec<bool>, Vec<&RouteDef>)> = None;
    for r in ROUTES {
        let Some(key) = match_key(r.segs, &raw) else {
            continue;
        };
        match &mut best {
            Some((k, group)) if *k == key => group.push(r),
            Some((k, _)) if key < *k => best = Some((key, vec![r])),
            Some(_) => {}
            None => best = Some((key, vec![r])),
        }
    }
    let Some((_, group)) = best else {
        return fallback();
    };
    let query = query.map(parse_query).unwrap_or_default();
    let params = |r: &RouteDef| -> Vec<String> {
        r.segs
            .iter()
            .zip(&raw)
            .filter_map(|(s, v)| match s {
                Seg::Param => Some(percent_decode(v, false)),
                Seg::Lit(_) => None,
            })
            .collect()
    };
    let m = Method::from_http(method);
    let find = |want: Method| group.iter().copied().find(|r| r.method == want);
    if let Some(r) = m.and_then(find) {
        return call(r.id, params(r), &query);
    }
    if m == Some(Method::Head)
        && let Some(r) = find(Method::Get)
    {
        let mut res = call(r.id, params(r), &query);
        res.body.clear();
        return res;
    }
    let allowed = allow(group.iter().map(|r| r.method));
    let status = if m == Some(Method::Options) { 204 } else { 405 };
    reply(status, vec![("allow".to_string(), allowed)], Vec::new(), None)
}

fn into_response(reply: Reply) -> Response<Body> {
    let mut res = Response::new(Body::from(reply.body));
    *res.status_mut() =
        StatusCode::from_u16(reply.status).unwrap_or(StatusCode::INTERNAL_SERVER_ERROR);
    for (name, value) in reply.headers {
        // A value holding a control character is not a header value (RFC 9110 §5.5); it is
        // dropped, as `mz contract`'s evaluator drops it.
        if let (Ok(n), Ok(v)) = (
            HeaderName::from_bytes(name.as_bytes()),
            HeaderValue::from_bytes(value.as_bytes()),
        ) {
            res.headers_mut().append(n, v);
        }
    }
    res
}

async fn handle(req: Request) -> Response<Body> {
    let target = req
        .uri()
        .path_and_query()
        .map(|p| p.as_str().to_string())
        .unwrap_or_else(|| "/".to_string());
    into_response(dispatch(req.method().as_str(), &target))
}

/// The service as an axum `Router`: one fallback, which is the whole of RFC-0011 §6.
pub fn app() -> Router {
    Router::new().fallback(handle)
}

#[tokio::main]
async fn main() {
    let port = std::env::var("PORT")
        .ok()
        .and_then(|p| p.parse::<u16>().ok())
        .unwrap_or(8080);
    let listener = match tokio::net::TcpListener::bind(("127.0.0.1", port)).await {
        Ok(l) => l,
        Err(e) => {
            eprintln!("cannot listen on 127.0.0.1:{port}: {e}");
            std::process::exit(1);
        }
    };
    println!("listening on http://127.0.0.1:{port}");
    if let Err(e) = axum::serve(listener, app()).await {
        eprintln!("server stopped: {e}");
        std::process::exit(1);
    }
}
"##;

const TESTS_HEAD: &str = r##"
// ---- the tests: one per `example`, sent to the router in process ----

#[cfg(test)]
mod tests {
    use super::*;
    use http_body_util::BodyExt;
    use tower::ServiceExt;

    struct Got {
        status: u16,
        headers: Vec<(String, String)>,
        body: Vec<u8>,
    }

    async fn send(method: &str, target: &str) -> Got {
        let req = axum::http::Request::builder()
            .method(method)
            .uri(target)
            .body(Body::empty())
            .expect("the example's request is valid");
        let res = app().oneshot(req).await.expect("the router is infallible");
        let status = res.status().as_u16();
        let headers = res
            .headers()
            .iter()
            .map(|(n, v)| (n.as_str().to_string(), String::from_utf8_lossy(v.as_bytes()).into_owned()))
            .collect();
        let body = res.into_body().collect().await.expect("a body").to_bytes().to_vec();
        Got { status, headers, body }
    }

    fn describe(g: &Got) -> String {
        format!("got {} {:?} {:?}", g.status, g.headers, String::from_utf8_lossy(&g.body))
    }

    enum F {
        Status,
        Header(&'static str),
        Body,
        Path(&'static str),
    }

    enum L {
        Int(i64),
        Text(&'static str),
        Bool(bool),
        None,
    }

    enum P {
        Is(L),
        In(&'static [L]),
        NotEmpty,
        Contains(&'static str),
        AtLeast(i64),
        AtMost(i64),
    }

    enum Read {
        Num(f64),
        Text(String),
        Absent,
        Json(serde_json::Value),
    }

    /// RFC-0011 §7's predicates, as `mz contract` judges them.
    fn holds(g: &Got, f: F, p: P) -> bool {
        let read = match f {
            F::Status => Read::Num(g.status as f64),
            F::Header(n) => match g.headers.iter().find(|(k, _)| k == n) {
                Some((_, v)) => Read::Text(v.clone()),
                None => Read::Absent,
            },
            F::Body => Read::Text(String::from_utf8_lossy(&g.body).into_owned()),
            F::Path(ptr) => match serde_json::from_slice::<serde_json::Value>(&g.body) {
                Ok(v) => match v.pointer(ptr) {
                    Some(x) => Read::Json(x.clone()),
                    None => return false,
                },
                Err(_) => return false,
            },
        };
        let num = match &read {
            Read::Num(n) => Some(*n),
            Read::Json(v) => v.as_f64(),
            _ => None,
        };
        let text = match &read {
            Read::Text(t) => Some(t.clone()),
            Read::Json(serde_json::Value::String(s)) => Some(s.clone()),
            _ => None,
        };
        let is = |l: &L| match l {
            L::Int(n) => num == Some(*n as f64),
            L::Text(t) => text.as_deref() == Some(*t),
            L::Bool(b) => matches!(&read, Read::Json(serde_json::Value::Bool(x)) if x == b),
            L::None => matches!(&read, Read::Absent | Read::Json(serde_json::Value::Null)),
        };
        match p {
            P::Is(l) => is(&l),
            P::In(set) => set.iter().any(is),
            P::NotEmpty => match &read {
                Read::Text(t) => !t.trim().is_empty(),
                Read::Json(serde_json::Value::String(s)) => !s.trim().is_empty(),
                Read::Json(serde_json::Value::Array(a)) => !a.is_empty(),
                Read::Json(serde_json::Value::Object(o)) => !o.is_empty(),
                _ => false,
            },
            P::Contains(t) => text.is_some_and(|x| x.contains(t)),
            P::AtLeast(n) => num.is_some_and(|x| x >= n as f64),
            P::AtMost(n) => num.is_some_and(|x| x <= n as f64),
        }
    }
"##;
