#!/usr/bin/env node
/**
 * Inline `openapi.yaml` into a module `GET /api/openapi` can import.
 *
 * The route used to do this:
 *
 *     const yamlPath = join(process.cwd(), "openapi.yaml")
 *     const yaml = await readFile(yamlPath, "utf-8")
 *
 * which is a filesystem read at request time. Cloudflare Workers has no
 * filesystem, so it throws — and the route's `catch` turns any throw into
 * `404 {"error":"OpenAPI specification not found"}`. The spec would simply
 * vanish from the public API, reported as absent rather than as broken.
 *
 * This is the same treatment already given to skills, doctrine, the registry
 * index and registry source. It was missed because those four live in `lib/`
 * and this one lives in `app/api/`, so an inventory of `lib/` could not see it.
 *
 * The artifact is the file's BYTES, not a parsed structure. Emitting parsed
 * YAML would make this a second parser that can disagree with whatever reads
 * the spec — and the route's job is to hand over the document as authored.
 *
 * Usage:
 *   node scripts/generate-openapi.mjs           write the artifact
 *   node scripts/generate-openapi.mjs --check   fail if it is out of date
 */

import { readFileSync, writeFileSync } from "node:fs"
import { join, dirname, relative } from "node:path"
import { fileURLToPath } from "node:url"

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..")
const SOURCE = join(ROOT, "openapi.yaml")
const OUT = join(ROOT, "lib", "openapi.generated.ts")

const yaml = readFileSync(SOURCE, "utf8")

const output = `// GENERATED by scripts/generate-openapi.mjs from openapi.yaml — do not edit.
//
// The OpenAPI document, inlined so \`GET /api/openapi\` can serve it without a
// filesystem. Regenerate with \`pnpm openapi:generate\`; CI runs
// \`pnpm openapi:generate:check\`.

/** \`openapi.yaml\` verbatim, ${yaml.length} bytes. */
export const OPENAPI_YAML = ${JSON.stringify(yaml)}
`

if (process.argv.includes("--check")) {
  let current = ""
  try {
    current = readFileSync(OUT, "utf8")
  } catch {
    console.error("✗ lib/openapi.generated.ts is missing. Run `pnpm openapi:generate`.")
    process.exit(1)
  }
  if (current !== output) {
    console.error(
      "✗ lib/openapi.generated.ts is out of date with openapi.yaml. Run `pnpm openapi:generate`."
    )
    process.exit(1)
  }
  console.log(`✓ openapi.yaml in sync — ${yaml.length} bytes`)
} else {
  writeFileSync(OUT, output)
  console.log(`✓ wrote ${relative(ROOT, OUT)} — ${yaml.length} bytes`)
}
